[package]
name = "sdr_api_test"
version = "0.1.0"
authors = ["Vincent <perrier.vincent0210@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtlsdr = "0.1.4"
